from app.email.constants import (
    POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
    POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
)
from app.email.enums import EmailEventType, SenderType
from app.email.schemas import EmailEventConfig


EMAIL_EVENT_REGISTRY = {
    EmailEventType.WELCOME_EMAIL: EmailEventConfig(
        event_type=EmailEventType.WELCOME_EMAIL,
        sender=SenderType.HELLO,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Welcome to SpeakerPitcher",
            "preheader": "Your account is ready to explore speaking opportunities.",
            "badge": "Welcome",
            "title": "Welcome to SpeakerPitcher",
            "intro": "We are excited to have you here.",
            "body": "Your profile is the foundation for better speaking opportunity matches.",
            "cta_text": "Open SpeakerPitcher",
            "secondary_note": "Need help? Reply to this email and our team will support you.",
        },
    ),
    EmailEventType.PASSWORD_RESET: EmailEventConfig(
        event_type=EmailEventType.PASSWORD_RESET,
        sender=SenderType.HELLO,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Reset your SpeakerPitcher password",
            "preheader": "Use this secure reset flow to regain account access.",
            "badge": "Security",
            "title": "Reset your password",
            "intro": "We received a password reset request for your account.",
            "body": "If this was you, continue using the secure reset action below.",
            "cta_text": "Reset Password",
            "secondary_note": "If you did not request this, you can ignore this email.",
        },
    ),
    EmailEventType.ACCOUNT_CONFIRMATION: EmailEventConfig(
        event_type=EmailEventType.ACCOUNT_CONFIRMATION,
        sender=SenderType.HELLO,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Confirm your SpeakerPitcher account",
            "preheader": "One step left to activate your account.",
            "badge": "Account",
            "title": "Confirm your account",
            "intro": "Please verify your email address to complete setup.",
            "body": "This keeps your account secure and enables full platform access.",
            "cta_text": "Confirm Account",
            "secondary_note": "If you did not create this account, you can ignore this message.",
        },
    ),
    EmailEventType.SYSTEM_NOTIFICATION: EmailEventConfig(
        event_type=EmailEventType.SYSTEM_NOTIFICATION,
        sender=SenderType.HELLO,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "SpeakerPitcher update",
            "preheader": "Important update from SpeakerPitcher.",
            "badge": "Update",
            "title": "Product update",
            "intro": "We have an update for you.",
            "body": "Please review the details and take action if needed.",
            "cta_text": "View Details",
            "secondary_note": "You are receiving this because you have an active SpeakerPitcher account.",
        },
    ),
    EmailEventType.ALERT_PITCH_READY: EmailEventConfig(
        event_type=EmailEventType.ALERT_PITCH_READY,
        sender=SenderType.ALERTS,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Your pitch is ready",
            "preheader": "Your draft pitch is complete and ready for review.",
            "badge": "Action Required",
            "title": "Your pitch is ready",
            "intro": "Great news, your pitch draft is now prepared.",
            "body": "Review your pitch now and make any final edits before sending.",
            "cta_text": "Review Pitch",
            "secondary_note": "This message is from alerts@speakerpitcher.ai.",
        },
    ),
    EmailEventType.ALERT_NEW_OPPORTUNITY: EmailEventConfig(
        event_type=EmailEventType.ALERT_NEW_OPPORTUNITY,
        sender=SenderType.ALERTS,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "New opportunity found",
            "preheader": "A relevant opportunity is waiting for your action.",
            "badge": "Opportunity",
            "title": "New opportunity found",
            "intro": "We found a speaking opportunity that matches your profile.",
            "body": "Open the opportunity details and submit your pitch while it is fresh.",
            "cta_text": "View Opportunity",
            "secondary_note": "This message is from alerts@speakerpitcher.ai.",
        },
    ),
    EmailEventType.ALERT_SUBMISSION_REMINDER: EmailEventConfig(
        event_type=EmailEventType.ALERT_SUBMISSION_REMINDER,
        sender=SenderType.ALERTS,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Reminder to submit",
            "preheader": "Do not miss your pending submission.",
            "badge": "Reminder",
            "title": "Reminder to submit",
            "intro": "You have a pending pitch submission.",
            "body": "Take a moment to finalize and submit your pitch.",
            "cta_text": "Submit Now",
            "secondary_note": "This message is from alerts@speakerpitcher.ai.",
        },
    ),
    EmailEventType.ALERT_DEADLINE_APPROACHING: EmailEventConfig(
        event_type=EmailEventType.ALERT_DEADLINE_APPROACHING,
        sender=SenderType.ALERTS,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Deadline approaching",
            "preheader": "A submission deadline is near.",
            "badge": "Urgent",
            "title": "Deadline approaching",
            "intro": "A speaking opportunity deadline is approaching soon.",
            "body": "Complete your submission now to avoid missing this deadline.",
            "cta_text": "Complete Submission",
            "secondary_note": "This message is from alerts@speakerpitcher.ai.",
        },
    ),
    EmailEventType.SUPPORT_CUSTOMER_SUPPORT: EmailEventConfig(
        event_type=EmailEventType.SUPPORT_CUSTOMER_SUPPORT,
        sender=SenderType.SUPPORT,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Customer support update",
            "preheader": "Your support request has an update.",
            "badge": "Support",
            "title": "Customer support",
            "intro": "Our support team has reviewed your request.",
            "body": "Please review the latest support response and continue the thread if needed.",
            "cta_text": "View Support Ticket",
            "secondary_note": "This message is from support@speakerpitcher.ai.",
        },
    ),
    EmailEventType.SUPPORT_HELP_REQUEST: EmailEventConfig(
        event_type=EmailEventType.SUPPORT_HELP_REQUEST,
        sender=SenderType.SUPPORT,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Help request received",
            "preheader": "We received your help request.",
            "badge": "Help",
            "title": "Help request",
            "intro": "Thanks for contacting support.",
            "body": "We have received your request and will follow up shortly with next steps.",
            "cta_text": "View Request",
            "secondary_note": "This message is from support@speakerpitcher.ai.",
        },
    ),
    EmailEventType.SUPPORT_BILLING_QUESTION: EmailEventConfig(
        event_type=EmailEventType.SUPPORT_BILLING_QUESTION,
        sender=SenderType.SUPPORT,
        template_id=POSTMARK_TEMPLATE_ID_SPEAKERPITCHER,
        template_alias=POSTMARK_TEMPLATE_ALIAS_SPEAKERPITCHER,
        defaults={
            "subject": "Billing support response",
            "preheader": "Update on your billing question.",
            "badge": "Billing",
            "title": "Billing question",
            "intro": "Our billing team has reviewed your question.",
            "body": "Please review the billing details and reply if you need anything else.",
            "cta_text": "Review Billing Details",
            "secondary_note": "This message is from support@speakerpitcher.ai.",
        },
    ),
}

